version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - myboot
    ports:
      - "27017:27017"
    restart: always
  webserver:
    image: kwjdgh/taba
    container_name: webserver
    depends_on:
      - mongodb
    networks:
      - myboot
    ports:
      - "8080:8080"
    restart: always

networks:
  myboot:
    driver: bridge
